name: antibody-lite
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8   # CPU 环境就删掉这一行
  - numpy>=1.23
  - pandas>=1.5
  - scikit-learn>=1.3
  - joblib
  - pyyaml
  - biopython
  - matplotlib
  - seaborn
  - tqdm
  - pip
  - pip:
      - esm==2.0.0
      - rich
